apiVersion: v1
kind: Service
metadata:
  name: flask-metrics-service
  namespace: monitoring
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - name: metrics
      protocol: TCP
      port: 8000         # External port for Prometheus to scrape
      targetPort: 5002    # Flask app's internal port
  type: ClusterIP
