{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: {{ .Values.prometheus.serviceMonitor.namespace | default "monitoring" }}  # Uses namespace from values.yaml
  labels:
    app: flask-app
    {{- with .Values.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: flask-app  # Must match the Service labels
  endpoints:
    - port: http   # Must match the named port in your Service definition
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
{{- end }}
