apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: monitoring  # Replace with the actual namespace where Prometheus is installed
  labels:
    app: flask-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask-app  # Must match the Service labels
  endpoints:
    - port: http   # Must match the named port in your Service definition
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default  # Ensure this matches the namespace where your Flask app runs
