apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: default
  labels:
    app: vault
spec:
  selector:
    app.kubernetes.io/name: vault
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
  type: LoadBalancer
