apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: 25.8.0  # Set the desired version (25.8.0)
    path: charts/kube-prometheus-stack  # Path to the chart directory in the GitHub repository
    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: "15d"  # Optional: Set Prometheus retention period
        thanosRuler:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true
      - ServerSideApply=true
