apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: main  # or a specific version like 'v25.7.0'
    path: charts/prometheus  # Path to the Prometheus chart in the GitHub repository
    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: "15d"  # Optional: Set retention period for Prometheus data
            resources:
              requests:
                memory: "400Mi"
                cpu: "200m"
              limits:
                memory: "800Mi"
                cpu: "500m"
          server:
            service:
              type: LoadBalancer  # Set the service type to LoadBalancer
              port: 9090          # Ensure it's using the correct port for Prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring  # Ensure the monitoring namespace exists or let ArgoCD create it
  syncPolicy:
    automated:
      prune: true  # Automatically remove resources if the application is deleted
      selfHeal: true  # Automatically re-sync the application if it's out of sync
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true
      - ServerSideApply=true
