apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: 25.8.0  # or specify a version tag like v25.7.0
    path: charts/prometheus  # Path to the Prometheus chart in the repository
    helm:
      values: |
        prometheus:
          prometheusSpec:
            retention: "15d"  # Optional: Set retention period for Prometheus data
          # Add additional configuration if needed for your Prometheus instance
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring  # Ensure you have this namespace created
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true
      - ServerSideApply=true
