apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}
  MYSQL_USER: {{ .Values.mysql.user | b64enc }}
  MYSQL_DB: {{ .Values.mysql.database | b64enc }}
