apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.targetPort }}
  clusterIP: {{ .Values.mysql.clusterIP }}
