apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app    # Add a label for filtering
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
