apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-logs-dashboard
  namespace: monitoring  # Ensure this matches Grafana's namespace
  labels:
    grafana_dashboard: "1"
data:
  loki-logs-dashboard.json: |
    {
      "title": "Flask App Logs",
      "schemaVersion": 40,
      "version": 1,
      "refresh": "5s",
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "panels": [
        {
          "title": "Flask App Logs",
          "type": "logs",
          "datasource": { "type": "loki", "uid": "loki" },
          "targets": [
            {
              "expr": "{app=\"flask-app\"} |= \"\"",
              "refId": "A"
            }
          ],
          "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
          "options": {
            "showLabels": true,
            "wrapLogMessage": true,
            "sortOrder": "Descending"
          }
        }
      ]
    }
