apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.3.4
    helm:
         values: |
          adminPassword: "admin"
          service:
            type: LoadBalancer
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard  # Ensures dashboards from ConfigMaps are loaded
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Ensure the namespace is created
      - PruneLast=true        # Prevent ArgoCD from deleting the namespace