replicaCount: 1

image:
  repository: sagisen/flaskaws
  tag: "0.0.0.114"
  pullPolicy: IfNotPresent

mysql:
  image: mysql:8.0
  database: mydb
  user: root
  password: "DataL123"
  serviceName: mysql-service
  replicas: 1
  port: 3306
  targetPort: 3306
  clusterIP: None
  passwordKey: MYSQL_PASSWORD
  databaseKey: MYSQL_DB
  secretName: mysql-secrets  # ✅ Add this to reference secrets in Helm templates
metrics:
  port: 8080  # Adjust the port where your Flask app exposes the /metrics endpoin
service:
  type: LoadBalancer
  port: 80
  targetPort: 5002


# Add this block to enable ServiceMonitor in Prometheus
prometheus:
  serviceMonitor:
    enabled: true
    additionalLabels: {}
    namespace: monitoring